### ISSUE TITLE
PHP version badge

### ISSUE THREAD

**Issue by alecrabbit** [kylekatarnls/multi-tester#2]
Please consider adding this badge to README.md
```
[![PHP Version](https://img.shields.io/packagist/php-v/kylekatarnls/multi-tester.svg)](https://php.net)
```
[![PHP Version](https://img.shields.io/packagist/php-v/kylekatarnls/multi-tester.svg)](https://php.net)

> or from other service (I mean instead of `shields.io`)

**Comment by kylekatarnls** [comment]
Hi,

It's reasonable. May I also ask what you were looking for when searching for the PHP minimum version?

Not sure the library was for PHP projects?
Needed a particular compatibility according to your own project?
Needed to run multi-tester on a machine that has an old PHP version?

Because even if you create a library for PHP 5.3 for example, you not necessarily need to run multi-tester with your minimal PHP version, you can have your own unit tests that will check the PHP 5.3 compatibility, then multi-tester could tests your package in other libraries using a different/newer PHP version.

For instance, I have projects that runs from PHP 5.x and I run unit tests of the project in each PHP version, then I run multi-tester only in PHP 7.3 because the purpose of multi-tester is not to check if the project works with every PHP versions, but it's to check if other libraries that use my package still work as expected with the last changes of my package and as PHP versions are already checked by unit-tests, it should not impact the multi-tester results until the packages you test would have some very specific logic with PHP version, such as:

```php
if (version_compare(PHP_VERSION, '5.6.0', '<')) {
    // do something with the project to test
}
```

So you can have some PHP project with PHP 5.3 as minimum version and still use multi-tester efficiently.

**Comment by alecrabbit** [comment]
Ok, here is the situation:
I had to test run an old project on php 5.6 and I was unsure if I can install multi-tester
to find out I had to open `composer.json` file
so, I suggested badge just for convenience

**Comment by alecrabbit** [comment]
btw thanks for adding the badge!
